ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email VARCHAR(320);

ALTER TABLE users
  ALTER COLUMN phone DROP NOT NULL;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_unique
  ON users (LOWER(email))
  WHERE email IS NOT NULL;
